spring:
  datasource:
    url: jdbc:postgresql://192.168.1.103:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  image:
    storage:
      path: ./annonces-images