INSERT INTO annonce (titre, description, categorie, prix, localisation, posted_at)
VALUES ('Vélo de montagne', 'Vélo de montagne en très bon état, utilisé une seule saison.', 'Sport', 450.00,
        'Paris, France', '2024-09-01'),
       ('Canapé en cuir', 'Canapé en cuir noir, trois places, presque neuf.', 'Mobilier', 1200.00, 'Lyon, France',
        '2024-08-15'),
       ('Smartphone Samsung', 'Samsung Galaxy S21, 128GB, avec tous les accessoires.', 'Électronique', 699.99,
        'Marseille, France', '2024-09-03'),
       ('Table basse en bois', 'Table basse en chêne massif, style rustique.', 'Mobilier', 300.00, 'Bordeaux, France',
        '2024-07-25'),
       ('Cours de piano', 'Professeur expérimenté donne cours de piano à domicile.', 'Services', 40.00, 'Nice, France',
        '2024-09-02'),
       ('Télévision 4K', 'TV 4K 55 pouces, avec télécommande et support mural.', 'Électronique', 850.00,
        'Nantes, France', '2024-08-29'),
       ('Vente maison', 'Belle maison de 120m² avec jardin et piscine.', 'Immobilier', 350000.00, 'Toulouse, France',
        '2024-09-04'),
       ('Chaussures de sport', 'Chaussures de sport Nike, taille 42, neuves.', 'Vêtements', 75.00, 'Lille, France',
        '2024-08-20'),
       ('Sac à dos randonnée', 'Sac à dos de randonnée 50L, parfait pour les longs treks.', 'Sport', 120.00,
        'Grenoble, France', '2024-08-10'),
       ('Cours d’anglais', 'Cours particuliers d’anglais pour tous niveaux.', 'Services', 30.00, 'Strasbourg, France',
        '2024-09-05');
